spring:
  data:
    mongodb:
      uri: mongodb+srv://asatdbadmin:Dhaka%40%232024@asatmongodb.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: springboot_auditing